# Basic Information 
title: Felix Taschbacch
position: PhD Candidate
affiliation: University of California San Diego
affiliation_link: https://ucsd.edu/
email: ftaschbach (at) ucsd.edu

# Search Engine Optimization (SEO)
keywords: felix taschbach
canonical: https://www.felix.phd/
description: Felix Taschbach is a Ph.D. candidate at UCSD. His research lies on the intersection of computational and behavioral neuroscience.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=tytm25sAAAAJ
# cv_link: https://files.yliu.me/Yaoyao_Liu_Curriculum_Vitae.pdf
github_link: https://github.com/FelixHT/
# linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: https://twitter.com/felixtaschbach/

# Images 
avatar: https://img.yliu.me/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
